name: HubCommand
main: work.fzhdev.hubcmd.Main
version: "1.0"
author: FengZhiHaiDevTeam
api: ["1.0.8"]
description: Back to lobby
permissions:
  plugin.hub:
    description: "Back to lobby"
    default: true
commands:
  hub:
    description: "Back to lobby"
    usage: "/hub"
    permission: plugin.hub
  lobby:
    description: "Back to lobby"
    usage: "/lobby"
    permission: plugin.hub
  l:
    description: "Back to lobby"
    usage: "/l"
    permission: plugin.hub